  steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'us-east1-docker.pkg.dev/einfo2024/services/devops-image-itau-julio:$COMMIT_SHA', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'us-east1-docker.pkg.dev/einfo2024/services/devops-image-itau-julio:$COMMIT_SHA']
      timeout: 2400s    
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run', 'deploy', 'devops-itau-julio', '--image', 'us-east1-docker.pkg.dev/einfo2024/services/devops-image-itau-julio:$COMMIT_SHA', '--region', 'us-east1']
  images:
    - 'us-east1-docker.pkg.dev/einfo2024/services/devops-image-itau-julio'
  options:
    logging: CLOUD_LOGGING_ONLY  